---
title: "Summary Stats"
output: pdf_document
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = TRUE, results = "asis")
```

```{r hide_stuff, include = FALSE}
library(tidyverse); library(here); library(summarytools)
reqd_stats <- function(i) descr(i, stats = c("min", "q1", "med", "mean", "sd", "q3", "max"),
                                style = "rmarkdown")
f1 <- read_csv(here("process_data", "diffs_ovr.csv")) %>% select(-GEOID)
f2 <- read_csv(here("process_data", "diffs_co.csv")) %>% select(-GEOID)
f3 <- read_csv(here("process_data", "diffs_reg.csv")) %>% select(-GEOID)
f4 <- read_csv(here("process_data", "ratios_ovr.csv")) %>% select(-GEOID)
f5 <- read_csv(here("process_data", "ratios_co.csv")) %>% select(-GEOID)
f6 <- read_csv(here("process_data", "ratios_reg.csv")) %>% select(-GEOID)
```

# Absolute difference 1990-2017
```{r f1, warning = FALSE, message = FALSE, echo = FALSE}
reqd_stats(f1)
```

# Absolute difference 1990-2017 relative to county mean
```{r f2, warning = FALSE, message = FALSE, echo = FALSE}
reqd_stats(f2)
```

# Absolute difference 1990-2017 relative to regional mean
```{r f3, warning = FALSE, message = FALSE, echo = FALSE}
reqd_stats(f3)
```

# Percentage difference 1990-2017
```{r f4, warning = FALSE, message = FALSE, echo = FALSE}
reqd_stats(f4)
```

# Percentage difference 1990-2017 relative to county mean
```{r f5, warning = FALSE, message = FALSE, echo = FALSE}
reqd_stats(f5)
```

# Percentage difference 1990-2017 relative to regional mean
```{r f6, warning = FALSE, message = FALSE, echo = FALSE}
reqd_stats(f6)
```